#!/bin/sh

set -e

# creating plugdev group if he isn't already there
if ! getent group plugdev >/dev/null; then
        addgroup --system plugdev
fi

# creating usbmux user if he isn't already there
if ! getent passwd usbmux >/dev/null; then
        adduser --system --ingroup plugdev \
                --home /var/lib/usbmux --no-create-home \
                --gecos "usbmux daemon" \
                usbmux
fi

# Automatically added by dh_installsystemd/13.6ubuntu1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		deb-systemd-invoke $_dh_action 'usbmuxd.service' >/dev/null || true
	fi
fi
# End automatically added section

